/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./pages/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}", "./app/**/*.{js,ts,jsx,tsx,mdx}"],
	theme: {
		extend: {
			backgroundImage: {
				"gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
				"gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
				"gradient-user-card": "linear-gradient(0deg, rgba(0, 0, 0, 0.63) 0%, rgba(0, 0, 0, 0.00) 100%)",
				"aside-section-pattern": "url('/public/images/dashboard/home/aside-section-pattern.png')",
				// "contact-us": "url('../public/images/contact-us/contact-us-1.png')",
			},
			boxShadow: {
				chat: "0px 4px 6px -2px rgba(16, 24, 40, 0.02), 0px 12px 16px -4px rgba(16, 24, 40, 0.04)",
			},
			colors: {
				"sky-blue": {
					DEFAULT: "#E1F2FE",
				},
				purple: {
					DEFAULT: "#350E9E",
				},
				blue: {
					dark: "#2E3A9E",
					"very-light": "#F0F9FF",
					"quin-light": "#F4F5FE",
					focused: "#4756D1",
					hover: "#3849C1",
					DEFAULT: "#465BF1",
					secondary: "#7685FA",
					tertiary: "#98A3FB",
					quat: "#BBC3FD",
					quin: "#DDE1FE",
					senary: "#F5F6FF",
					backdrop: "#fafaff",
				},
				black: {
					DEFAULT: "#0D2247",
					secondary: "#41415A",
					tertiary: "#71748C",
					quat: "#B8BAC6",
					quin: "#D5D5DD",
					deep: "#202030",

					"nav-bg": "rgba(0, 0, 0, .1)",
				},
				white: {
					DEFAULT: "#ffff",
					light: "#FAFAFF",
					grey: "#F7F9FC",
					"nav-bg": "rgba(255, 255, 255, .1)",
					"dash-bg": "#f5f5f5",
				},
				grey: {
					secondary: "#F1F1F4",
					tertiary: "#F6F7F8",
					quat: "#DDDDDD",
					quin: "#AAAAAA",
					backdrop: "#F9F9FB",
					DEFAULT: "#E3E3E8",
				},
				error: {
					DEFAULT: "#D20832",
					secondary: "#DB3959",
					tertiary: "#E46B84",
					quat: "#ED9CAC",
					quin: "#F6CED6",
					backdrop: "#FDF6F8",
					deep: "#D42952",
				},
				success: {
					DEFAULT: "#22B231",
					secondary: "#4EC15A",
					tertiary: "#7AD183",
					quat: "#A7E0AD",
					quin: "#D3F0D6",
					backdrop: "#F7FCF8",
					deep: "#1CCE82",
				},
				warning: {
					DEFAULT: "#F07911",
					secondary: "#F39441",
					tertiary: "#F49B4D",
					quat: "#F8BC88",
					quin: "#FBDEC4",
					backdrop: "#FEFAF5",
				},
				info: {
					text: "#139AB7",
					bg: "#F2F6FB",
					DEFAULT: "#139AB7",
					secondary: "#42AEC5",
					tertiary: "#71C2D4",
					quat: "#A1D7E2",
					quin: "#D0EBF1",
					backdrop: "#F7FCFD",
					deep: "#66C9FF",
				},
			},
			screens: {
				"5xl": "1200px",
				"5xs": "300px",
				"4xs": "380px",
				"3xs": "400px",
				"2xs": "475px",
				xs: "540px",
			},
		},
	},
	plugins: [],
};
