import "./globals.css";

// import {Averia_Libre} from "next/font/google";
import Footer from "./footer";
import Header from "./header";
import InitLoader from "@/components/general/init-loader/init-loader";
import ReactQueryWrapper from "@/components/react-query/react-query-wrapper";
import ReduxProvider from "@/redux/redux-provider";
import ToastContainer from "@/components/toast-container";
import localFont from "next/font/local";

// import {enableES5, enableMapSet} from "immer";

// import {QueryClient, QueryClientProvider} from "@tanstack/react-query";

// const Averia = Averia_Libre({weight: ["300", "400", "700"], subsets: ["latin"]});

// Font files can be colocated inside of `app`
const myFont = localFont({
	src: [
		{
			path: "./AvenirLTStd-Book.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./AvenirLTStd-Roman.otf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./AvenirLTStd-Black.otf",
			weight: "700",
			style: "normal",
		},
	],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// const queryClient = new QueryClient();
// enableES5();
// enableMapSet();

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={myFont.className}>
				<ReactQueryWrapper>
					<ReduxProvider>
						<div className="relative flex w-screen flex-grow flex-col items-start justify-start">
							<InitLoader />
							<ToastContainer />
							<Header />
							{children}
							<Footer />
						</div>
					</ReduxProvider>
				</ReactQueryWrapper>
			</body>
		</html>
	);
}
