import "./globals.css";

import {Averia_Libre} from "next/font/google";
import Footer from "./footer";
import Header from "./header";
import localFont from "next/font/local";

// const Averia = Averia_Libre({weight: ["300", "400", "700"], subsets: ["latin"]});

// Font files can be colocated inside of `app`
const myFont = localFont({
	src: [
		{
			path: "./AvenirLTStd-Book.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./AvenirLTStd-Roman.otf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./AvenirLTStd-Black.otf",
			weight: "700",
			style: "normal",
		},
	],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={myFont.className}>
				<div className="relative flex flex-col justify-start items-start min-h-screen w-screen">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
